# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5d47c2fe11bd6bb677d66e39b177cf2016ff4b4cb0e728813bda302e51c8cc6b6b4b6084baca18ea192d050c3412955f3da9fb699d9afd91cef31206eea48100

test:
  secret_key_base: 1409f01b9d7f3dcb022db19c0aaba1fdb5ef0cf82bfdb6b3f32e28e4b227da08c5ec92b5897df2fe9daec2ed5975c233d42c543d796d81d46151eed4cb721d1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
